sudo: false

language:
  - cpp

os:
  - osx

addons:
  homebrew:
    packages:
    - protobuf
    - grpc
    - etcd
    update: true

before_script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew services start etcd ; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
